features:
  - Total Items
  - Unique Items
  - Total Sales
  - Discounted Sales
  - Browsing Duration (minutes)
  - Number of Clicks
  - Age
  - Gender
  - Region
  - Marital Status
  - Education
  - Household Income
  - Loyalty Card
  - discount_pct
  - week_day
  - month
  - time_between_clicks
  - discount_to_time

rforest:
  n_estimators: 1000

gboost:
  n_estimators: 1000
  learning_rate: 0.1
  max_depth: 10

ada:
  n_estimators: 10000
  learning_rate: 0.01

xgboost:
  learning_rate: 0.001
  n_estimators: 4000
  gamma: 0.01
  subsample: 0.5
  colsample_bytree: 0.5
  objective: binary:logistic
  nthread: 4
  scale_pos_weight: 4
  max_depth: 1000
  min_child_weight: 20